<Workspace Version="1.3.0.875" X="264.9485319951" Y="255.65092943615" zoom="1.74331992875497" ScaleFactor="1" Name="BoundingBox.ToSectionBox" Description="Convert Dynamo BoundingBox to Revit Section Box, and apply it to the desired 3D view." ID="129edbe9-ac2d-4e67-9ed8-0fc8fa7667c0" Category="Zhukoven.Revit.BoundingBoxes">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="f25e4629-22af-4db2-a8ee-9b92e121808e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Based on the code originally posted by Dimitar Venkov
#Tested to work with Dynamo 1.3.0+
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
bbox = IN[0]
view = UnwrapElement(IN[1])
try:
    TransactionManager.Instance.EnsureInTransaction(doc)
    newmax = UnwrapElement(bbox.MaxPoint).ToRevitType()
    newmin = UnwrapElement(bbox.MinPoint).ToRevitType()
    newbox = BoundingBoxXYZ()
    newbox.Max = newmax
    newbox.Min = newmin

    z = view.SetSectionBox(newbox)

    OUT = "Done"
except:
    OUT = "Error"</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="81d007dc-e9f9-4366-8683-8a3e145836b8" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="91.3593603655991" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="BoundingBox" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="fa8a397d-af28-4ec6-a888-c5c175e34504" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="147.631430156004" y="57.9786152839255" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6851c19b-53c1-4b17-8520-2e399189f86b" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="391.403881508644" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f25e4629-22af-4db2-a8ee-9b92e121808e" start_index="0" end="6851c19b-53c1-4b17-8520-2e399189f86b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="81d007dc-e9f9-4366-8683-8a3e145836b8" start_index="0" end="f25e4629-22af-4db2-a8ee-9b92e121808e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fa8a397d-af28-4ec6-a888-c5c175e34504" start_index="0" end="f25e4629-22af-4db2-a8ee-9b92e121808e" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>