<Workspace Version="1.3.3.4111" X="392.07995598941" Y="309.960989563483" zoom="1.27771698410772" ScaleFactor="1" Name="RebarShape.GetCurves" Description="Generate curves for the rebar shape, as used in the shape browser." ID="eb17910d-f82f-4aab-8024-95ba2ce069b2" Category="Zhukoven.Revit.Rebar">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="170546bf-91bd-46e6-93c4-846bece1a9b3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.0+
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

RebarShape = UnwrapElement(IN[0])

for r in RebarShape:
	bCurves = r.GetCurvesForBrowser()
	curves = []
	for c in bCurves:
		curves.append(c.ToProtoType())

OUT = curves
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="43f164a4-d04d-4b39-bccf-fa72f038c66b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-234.662858507837" y="-0.474338645646412" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input rebar shape element&#xD;&#xA;RebarShape" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4defc8cf-1f42-4a8e-8e2b-ae890655d4ab" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Curves" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="70ad43bc-da05-4de4-a49f-637a67c0df7c" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="36.4355102311256" y="3.94637227744352" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="170546bf-91bd-46e6-93c4-846bece1a9b3" start_index="0" end="4defc8cf-1f42-4a8e-8e2b-ae890655d4ab" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="43f164a4-d04d-4b39-bccf-fa72f038c66b" start_index="0" end="70ad43bc-da05-4de4-a49f-637a67c0df7c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="70ad43bc-da05-4de4-a49f-637a67c0df7c" start_index="0" end="170546bf-91bd-46e6-93c4-846bece1a9b3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-575.590929621129" eyeY="2124.71532895886" eyeZ="1448.77702539666" lookX="678.695396270852" lookY="-2124.33223980516" lookZ="-999.068639570381" upX="0.417595304345439" upY="0.669130606358858" upZ="-0.614718141445709" />
  </Cameras>
</Workspace>