<Workspace Version="1.3.2.2480" X="246.987232328125" Y="288.91605509375" zoom="1.545620359375" ScaleFactor="1" Name="Room.Unplace" Description="Input room(s) that you wish to unplace (remove from the model views). These rooms would be stored in the project, and could be placed again in another location. " ID="39eb52f4-90d1-4c57-8ee1-b56f36b3c604" Category="Zhukoven.Revit.Rooms">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.List.__Create" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="0f7f5256-730f-4b4d-82e7-4401bb83f522" type="PythonNodeModels.PythonNode" nickname="Python Script" x="469.191783203112" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.0+
import clr
clr.AddReference("RevitNodes")
import Revit

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
rooms = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)

if isinstance(rooms, list):
	unplaceRooms = rooms.Unplace()
else:
	unplaceRooms = []
	for i in rooms:
		unplaceRooms.append(i.Unplace())
TransactionManager.Instance.TransactionTaskDone()

OUT = rooms
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fd2a3964-90f6-40a3-9088-636c936bbcc3" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="4.37603275423476" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e50f312e-f4cf-4234-b518-371fbe15aced" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="168.86423526767" y="0.646989407155843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Room" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="675cf47d-74b2-40f6-8362-c3367b21f2d7" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="612.550694187711" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Room" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="0f7f5256-730f-4b4d-82e7-4401bb83f522" start_index="0" end="675cf47d-74b2-40f6-8362-c3367b21f2d7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fd2a3964-90f6-40a3-9088-636c936bbcc3" start_index="0" end="0f7f5256-730f-4b4d-82e7-4401bb83f522" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e50f312e-f4cf-4234-b518-371fbe15aced" start_index="0" end="fd2a3964-90f6-40a3-9088-636c936bbcc3" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>