<Workspace Version="1.3.2.2480" X="293.908215745522" Y="258.058278266066" zoom="1.30764135636719" ScaleFactor="1" Name="Room.ByPhaseLevelActiveView" Description="Place room elements at the desired phase in the active view. Note that the phase of the active view would be changed to be aligned with the phase that you choose in Dynamo." ID="7cf39fd5-d729-4a85-b2c8-47ce09ccf50d" Category="Zhukoven.Revit.Rooms">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="73a8b08b-7a95-493d-aa04-035460953489" type="PythonNodeModels.PythonNode" nickname="Python Script" x="474.45447974721" y="106.110210772615" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.0+
import clr
clr.AddReference("RevitNodes")
import Revit

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *
from Autodesk.Revit.Creation.Document import NewRooms2

doc = DocumentManager.Instance.CurrentDBDocument
phase = UnwrapElement(IN[0])
lvl = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)
viewPhase = IN[2]
if viewPhase:
	createRoom = doc.Create.NewRooms2(lvl,phase)
	if isinstance(createRoom, list):
		roomElement = doc.GetElement(createRoom)
	else:
		roomElement = []
		for i in createRoom:
			roomElement.append(doc.GetElement(i))
TransactionManager.Instance.TransactionTaskDone()

OUT = roomElement
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="3a7808e4-5e9d-4be5-aa7e-72cdc7de54fa" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="ActiveView.SetPhase" x="250" y="28.0037414229482" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="a4822f50-9c30-45ca-8922-007281237cff" />
      <Name value="ActiveView.SetPhase" />
      <Description value="Input phase that you would like to set to the active view." />
      <Inputs>
        <Input value="Phase" />
      </Inputs>
      <Outputs>
        <Output value="View" />
        <Output value="Result" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8c0137a4-06d9-42e4-bbb0-61c3f5e19522" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="143.472961044663" y="106.110210772615" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Phase" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="57236099-b88d-4c0e-afa1-45cf16998e7c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="143.472961044663" y="167.186865125142" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Level" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="38cba6b4-431c-4ac8-bfba-169f65598e35" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="614.421334317375" y="106.110210772615" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="73a8b08b-7a95-493d-aa04-035460953489" start_index="0" end="38cba6b4-431c-4ac8-bfba-169f65598e35" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3a7808e4-5e9d-4be5-aa7e-72cdc7de54fa" start_index="1" end="73a8b08b-7a95-493d-aa04-035460953489" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8c0137a4-06d9-42e4-bbb0-61c3f5e19522" start_index="0" end="73a8b08b-7a95-493d-aa04-035460953489" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8c0137a4-06d9-42e4-bbb0-61c3f5e19522" start_index="0" end="3a7808e4-5e9d-4be5-aa7e-72cdc7de54fa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="57236099-b88d-4c0e-afa1-45cf16998e7c" start_index="0" end="73a8b08b-7a95-493d-aa04-035460953489" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>