<Workspace Version="1.3.4.6666" X="278.8" Y="190.1175" zoom="1.1575" ScaleFactor="1" Name="Sheet.Viewports" Description="Query viewports from the input sheet(s)." ID="b3663e08-33c6-40d0-85b3-c82f5a374d59" Category="Zhukoven.Revit.Views">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.String.Join" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DSCore.String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="2273787d-d452-4463-ad24-c8ce3f58644b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="462.53502372851" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.3+
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

sheets = UnwrapElement(IN[0])

viewports = []
for v in sheets:
	viewportIds = v.GetAllViewports()
	for i in viewportIds:
		elt = doc.GetElement(i)
		viewports.append(elt)
OUT = viewports
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ea382c5f-79d4-45b3-bd6f-53d4680c020b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="3.9463722774401" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="29203ded-a5a3-4621-94bc-67dd55167781" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="sheet(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="bb105a3b-d503-4ee5-b503-e19a9653e519" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="661.53502372851" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="viewports" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2273787d-d452-4463-ad24-c8ce3f58644b" start_index="0" end="bb105a3b-d503-4ee5-b503-e19a9653e519" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ea382c5f-79d4-45b3-bd6f-53d4680c020b" start_index="0" end="2273787d-d452-4463-ad24-c8ce3f58644b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="29203ded-a5a3-4621-94bc-67dd55167781" start_index="0" end="ea382c5f-79d4-45b3-bd6f-53d4680c020b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>