<Workspace Version="1.3.2.2480" X="77.1179590897021" Y="230.655882439221" zoom="1.51051845643135" ScaleFactor="1" Name="Stairs.GetStairsRuns" Description="This node returns all the stairs run components in the stairs." ID="d0ad7fcd-1db6-4f6a-8d9b-a10adbf8a700" Category="Zhukoven.Revit.Stairs">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="480c70ba-5147-4194-ae01-000f9954c007" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="4.38347696601818" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a4a8ed6a-e6e5-462d-a4f8-24ed331a0efc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-22.6446292504538" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input stair(s) element(s)&#xD;&#xA;Stair" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0da92f6d-8a5d-4b5b-8c71-84845878f663" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="611.223018412649" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="StairsRuns" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="2e218b30-2db9-4df1-a535-709a6d5ec93d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="471.266167153772" y="0.227814204661598" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Tested to work with Dynamo 1.3.0 + 
#Author © Konstantin Zhukoven @ https:\\zhukoven.com
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

stair = UnwrapElement(IN[0])
for i in stair:
	runs = i.GetStairsRuns()
	for i in runs:
		elt = doc.GetElement(i)
#Output
OUT = elt</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="480c70ba-5147-4194-ae01-000f9954c007" start_index="0" end="2e218b30-2db9-4df1-a535-709a6d5ec93d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a4a8ed6a-e6e5-462d-a4f8-24ed331a0efc" start_index="0" end="480c70ba-5147-4194-ae01-000f9954c007" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2e218b30-2db9-4df1-a535-709a6d5ec93d" start_index="0" end="0da92f6d-8a5d-4b5b-8c71-84845878f663" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>