<Workspace Version="1.3.0.875" X="-699.534305182145" Y="53.3082849284347" zoom="2.21436265193601" ScaleFactor="1" Name="UI.SelectionBox" Description="Activate Revit 3D selection box by selected elements." ID="97fa415f-ef3f-4b03-a334-6f1160287714" Category="Zhukoven.Revit.UI">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7474588a-0eaa-4bb3-96e1-a269d1189949" type="PythonNodeModels.PythonNode" nickname="Python Script" x="676.579232037423" y="107.62464967954" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc =  DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIDocument
app = DocumentManager.Instance.CurrentUIApplication.Application
uiapp = DocumentManager.Instance.CurrentUIApplication

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import *
output = []
postcmd = RevitCommandId.LookupPostableCommandId(PostableCommand.SelectionBox)
if IN[0] == True:
	uiapp.PostCommand(postcmd)
	output = True
else :
	output = 'Set RunIt to true'
OUT = output</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2d495154-cc1c-4736-b666-e13639a89d41" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="445.469048710109" y="107.402793145203" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RunIt : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b1f17610-3475-415c-bb0d-38ed819ce147" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="829.6" y="108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Result" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="7474588a-0eaa-4bb3-96e1-a269d1189949" start_index="0" end="b1f17610-3475-415c-bb0d-38ed819ce147" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2d495154-cc1c-4736-b666-e13639a89d41" start_index="0" end="7474588a-0eaa-4bb3-96e1-a269d1189949" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>