<Workspace Version="1.3.4.6666" X="228" Y="140" zoom="1" ScaleFactor="1" Name="Viewport.View" Description="Query the view associated with the input viewport." ID="dfd8ebb8-efa3-45a8-a0b0-4bd4c3737f1f" Category="Zhukoven.Revit.Views">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.String.Join" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="DSCore.String" resolvedName="DSCore.String" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="f5b858c8-75a3-4ec3-b43e-6d9bf0b9c2d6" type="PythonNodeModels.PythonNode" nickname="Python Script" x="462.535023728511" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.3+
import clr
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

viewports = UnwrapElement(IN[0])

views, elts = [], []
for v in viewports:
	vList = v.ViewId
	views.append(vList)
for i in views:
	elt = doc.GetElement(i)
	elts.append(elt)
OUT = elts</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="adfc88be-eaf9-494a-995d-35fab7506d97" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="250" y="3.94637227744352" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="40d22e55-497e-4d66-b935-0a2ffd574847" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="viewport(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b920d3e2-3a71-48df-afda-6f7f029e5ebd" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="661.535023728511" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="view" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f5b858c8-75a3-4ec3-b43e-6d9bf0b9c2d6" start_index="0" end="b920d3e2-3a71-48df-afda-6f7f029e5ebd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="adfc88be-eaf9-494a-995d-35fab7506d97" start_index="0" end="f5b858c8-75a3-4ec3-b43e-6d9bf0b9c2d6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="40d22e55-497e-4d66-b935-0a2ffd574847" start_index="0" end="adfc88be-eaf9-494a-995d-35fab7506d97" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>