<Workspace Version="1.3.0.875" X="432.288079215253" Y="226.497605775152" zoom="1.78359936238281" ScaleFactor="1" Name="WallSweep.GetProfile" Description="This node takes wall sweep elements and extracts their profiles. It works both with standard sweeps, and wall assemblies. " ID="867ac7aa-1161-470a-83a8-fe37d40e9bdd" Category="Zhukoven.Revit.Walls">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6c02988b-3f09-47c5-a200-a8b70f387195" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0.560664026401128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.0+
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

swp = UnwrapElement(IN[0])
swprofile = []
for i in swp:
	swprofile.append(doc.GetElement(i.GetWallSweepInfo().ProfileId))
#Output
OUT = swprofile</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9ac83d33-d09b-45ce-a8c5-8b798a72f1eb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-31.0554915434794" y="0.646989407155814" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input wall sweep elements&#xD;&#xA;WallSweep" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="98b15ea4-33cb-4ddc-8629-0ecac0366865" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="399.100901650301" y="1.1213280528022" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Profile" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6c02988b-3f09-47c5-a200-a8b70f387195" start_index="0" end="98b15ea4-33cb-4ddc-8629-0ecac0366865" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9ac83d33-d09b-45ce-a8c5-8b798a72f1eb" start_index="0" end="6c02988b-3f09-47c5-a200-a8b70f387195" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Фоновый просмотр" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>