<Workspace Version="1.3.4.6666" X="246.287451662365" Y="294.224537726687" zoom="1.24844365397223" ScaleFactor="1" Name="Workset.Create" Description="Create new worksets with the input names (strings) in the current document." ID="2799d1b0-11b3-4c17-8d73-930a058e0e6c" Category="Zhukoven.Revit.Worksharing">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="3861d35a-ba59-450f-b32a-d0533b5c037c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Author Konstantin Zhukoven @ https://zhukoven.com
#Tested to work with Dynamo 1.3.3+
import clr
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

names = IN[0]
newWorksets = []

wsTable = doc.GetWorksetTable()
for i in names:
	if wsTable.IsWorksetNameUnique(doc, i):
		# Start Transaction
		TransactionManager.Instance.EnsureInTransaction(doc)
		newWorksets.append(Workset.Create(doc,i))
		# End Transaction
		TransactionManager.Instance.TransactionTaskDone()
		OUT = newWorksets
	else:
		OUT = "Error: workset name is already in use"</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="042eb17d-d1b1-45f8-b9e2-a6855fbd3347" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-318.96577772782" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input workset name(s) as string(s)&#xD;&#xA;worksetName" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3d8e0a48-93d3-4dba-9ae4-b80029b3705c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="391.915058547675" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Workset element&#xD;&#xA;workset" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="40da81ee-cf83-46a1-9fe8-a6f75ff5217f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="25.7839342178374" y="4.12868426222428" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten({item});" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3861d35a-ba59-450f-b32a-d0533b5c037c" start_index="0" end="3d8e0a48-93d3-4dba-9ae4-b80029b3705c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="042eb17d-d1b1-45f8-b9e2-a6855fbd3347" start_index="0" end="40da81ee-cf83-46a1-9fe8-a6f75ff5217f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="40da81ee-cf83-46a1-9fe8-a6f75ff5217f" start_index="0" end="3861d35a-ba59-450f-b32a-d0533b5c037c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>